### PR TITLE
initial 0.13.10

### PR DESCRIPTION
**Pull request by M-Waszkiewicz-Anaconda**
aws-c-io 0.13.10

Destination channel: defaults

Links
[ticket_number](https://anaconda.atlassian.net/browse/PKG-3944)
[Upstream repository](https://github.com/awslabs/aws-c-io/tree/v0.13.10)
dependency for aws-c-event-stream 0.2.15 -> aws-sdk-cpp 1.10.55 -> arrow-cpp 14.0.1 -> pyarrow 14.0.1 which would address CVE

### CODE REVIEW

**Review by boldorider4 — APPROVED** [review]
LGTM

**Review by boldorider4 — COMMENTED** [review]
description section is missing in about section

**Review by danpetry — APPROVED** [review]
Don't know if you already know, but often when we're doing an older version than the most recent in the feedstock, we would create a version branch. It doesn't really matter here because there haven't been any significant changes since v0.13.10.

**Comment by M-Waszkiewicz-Anaconda** [comment]
> ally m

**Comment by M-Waszkiewicz-Anaconda** [comment]
> Don't know if you already know, but often when we're doing an older version than the most recent in the feedstock, we would create a version branch. It doesn't really matter here because there haven't been any significant changes since v0.13.10.

Yes, I know that, but this is the new feedstock, the diff you see is the forked one from CF we haven't released that feedstock yet

**Pull request merged**
